"""add fileds in paymenttable

Revision ID: 8f6b77f70a09
Revises: 
Create Date: 2026-05-28 09:44:51.355227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6b77f70a09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist')
    op.add_column('payments', sa.Column('gateway', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('gateway_order_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('gateway_payment_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('signature', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('payments', 'created_at')
    op.drop_column('payments', 'signature')
    op.drop_column('payments', 'gateway_payment_id')
    op.drop_column('payments', 'gateway_order_id')
    op.drop_column('payments', 'gateway')
    op.create_table('wishlist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='wishlist_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wishlist_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wishlist_pkey')
    )
    # ### end Alembic commands ###
