"""add user_id to payments

Revision ID: cb3a63a9c0db
Revises: 1c495deab141
Create Date: 2026-05-26 09:40:41.847524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3a63a9c0db'
down_revision: Union[str, Sequence[str], None] = '1c495deab141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('payments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'user_id')
    op.alter_column('categories', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
